rm -rf ./node_modules package.json;
npm i -D @babel/cli@latest;
npm i -D nodemon@latest;
    npm i -D @babel/core@latest;
    npm i -D @babel/helpers@latest;
    npm i -D @babel/plugin-proposal-class-properties@latest;
    npm i -D @babel/plugin-proposal-export-default-from@latest;
    npm i -D @babel/plugin-proposal-export-namespace-from@latest;
    npm i -D @babel/plugin-proposal-function-bind@latest;
    npm i -D @babel/plugin-proposal-object-rest-spread@latest;
    npm i -D @babel/plugin-proposal-throw-expressions@latest;
    npm i -D @babel/plugin-syntax-dynamic-import@latest;
    npm i -D @babel/plugin-transform-arrow-functions@latest;
    npm i -D @babel/plugin-transform-async-to-generator@latest;
    npm i -D @babel/plugin-transform-block-scoped-functions@latest;
    npm i -D @babel/plugin-transform-block-scoping@latest;
    npm i -D @babel/plugin-transform-classes@latest;
    npm i -D @babel/plugin-transform-destructuring@latest;
    npm i -D @babel/plugin-transform-exponentiation-operator@latest;
    npm i -D @babel/plugin-transform-function-name@latest;
    npm i -D @babel/plugin-transform-instanceof@latest;
    npm i -D @babel/plugin-transform-modules-commonjs@latest;
    npm i -D @babel/plugin-transform-new-target@latest;
    npm i -D @babel/plugin-transform-object-super@latest;
    npm i -D @babel/plugin-transform-parameters@latest;
    npm i -D @babel/plugin-transform-property-mutators@latest;
    npm i -D @babel/plugin-transform-react-constant-elements@latest;
    npm i -D @babel/plugin-transform-regenerator@latest;
    npm i -D @babel/plugin-transform-reserved-words@latest;
    npm i -D @babel/plugin-transform-runtime@latest;
    npm i -D @babel/plugin-transform-shorthand-properties@latest;
    npm i -D @babel/plugin-transform-spread@latest;
    npm i -D @babel/plugin-transform-template-literals@latest;
    npm i -D @babel/preset-react@latest;
    npm i -D @babel/runtime-corejs3@latest;
    npm i -D @babel/types@latest;
    npm i -D @svgr/webpack@latest;
    npm i -D autoprefix@latest;
    npm i -D babel-core@latest;
    npm i -D babel-eslint@latest;
    npm i -D babel-jest@latest;
    npm i -D babel-loader@latest;
    npm i -D babel-plugin-minify-constant-folding@latest;
    npm i -D babel-plugin-minify-simplify@latest;
    npm i -D babel-plugin-named-asset-import@latest;
    npm i -D babel-plugin-transform-async-to-module-method@latest;
    npm i -D babel-plugin-transform-inline-environment-variables@latest;
    npm i -D babel-plugin-transform-member-expression-literals@latest;
    npm i -D babel-plugin-transform-minify-booleans@latest;
    npm i -D babel-plugin-transform-property-literals@latest;
    npm i -D babel-plugin-transform-react-remove-prop-types@latest;
    npm i -D babel-preset-minify@latest;
    npm i -D babel-preset-react-app@latest;
    npm i -D body-parser@latest;
    npm i -D brotli-webpack-plugin@latest;
    npm i -D case-sensitive-paths-webpack-plugin@latest;
    npm i -D compression@latest;
    npm i -D compression-webpack-plugin@latest;
    npm i -D core-js@latest;
    npm i -D cors@latest;
    npm i -D css-loader@latest;
    npm i -D dotenv@latest;
    npm i -D dotenv-expand@latest;
    npm i -D enzyme@latest;
    npm i -D enzyme-adapter-react-16@latest;
    npm i -D enzyme-to-json@latest;
    npm i -D eslint@latest;
    npm i -D eslint-config-prettier@latest;
    npm i -D eslint-config-react-app@latest;
    npm i -D eslint-loader@latest;
    npm i -D eslint-plugin-flowtype@latest;
    npm i -D eslint-plugin-import@latest;
    npm i -D eslint-plugin-jest@latest;
    npm i -D eslint-plugin-jsx-a11y@latest;
    npm i -D eslint-plugin-prettier@latest;
    npm i -D eslint-plugin-react@latest;
    npm i -D eslint-plugin-react-hooks@latest;
    npm i -D express@latest;
    npm i -D express-static-gzip@latest;
    npm i -D file-loader@latest;
    npm i -D fs-extra@latest;
    npm i -D grunt@latest;
    npm i -D helmet@latest;
    npm i -D html-webpack-plugin@latest;
    npm i -D husky@latest;
    npm i -D i@latest;
    npm i -D identity-obj-proxy@latest;
    npm i -D ignore-styles@latest;
    npm i -D install@latest;
    npm i -D is-wsl@latest;
    npm i -D jest@latest;
    npm i -D jest-cli@latest;
    npm i -D jest-config@latest;
    npm i -D jest-css-modules@latest;
    npm i -D jest-environment-jsdom-fourteen@latest;
    npm i -D jest-extended@latest;
    npm i -D jest-pnp-resolver@latest;
    npm i -D jest-resolve@latest;
    npm i -D jest-watch-typeahead@latest;
    npm i -D mini-css-extract-plugin@latest;
    npm i -D nightmare@latest;
    npm i -D node-sass@latest;
    npm i -D npm@latest;
    npm i -D npm-run-all@latest;
    npm i -D optimize-css-assets-webpack-plugin@latest;
    npm i -D pnp-webpack-plugin@latest;
    npm i -D postcss-flexbugs-fixes@latest;
    npm i -D postcss-loader@latest;
    npm i -D postcss-normalize@latest;
    npm i -D postcss-preset-env@latest;
    npm i -D postcss-safe-parser@latest;
    npm i -D prettier@latest;
    npm i -D react-app-polyfill@latest;
    npm i -D react-dev-utils@latest;
    npm i -D react-hot-loader@latest;
    npm i -D react-test-renderer@latest;
    npm i -D redux-devtools-extension@latest;
    npm i -D redux-mock-store@latest;
    npm i -D redux-saga-test-plan@latest;
    npm i -D resolve@latest;
    npm i -D sass-lint@latest;
    npm i -D sass-loader@latest;
    npm i -D semver@latest;
    npm i -D style-loader@latest;
    npm i -D stylelint@latest;
    npm i -D stylelint-config-prettier@latest;
    npm i -D stylelint-config-standard@latest;
    npm i -D stylelint-order@latest;
    npm i -D terser-webpack-plugin@latest;
    npm i -D tmp@latest;
    npm i -D uglify-js-brunch@latest;
    npm i -D url-loader@latest;
    npm i -D webpack@latest;
    npm i -D webpack-bundle-analyzer@latest;
    npm i -D webpack-cli@latest;
    npm i -D webpack-dev-middleware@latest;
    npm i -D webpack-dev-server@latest;
    npm i -D webpack-hot-middleware@latest;
    npm i -D webpack-manifest-plugin@latest;
    npm i -D webpack-node-externals@latest;
    npm i -D workbox-webpack-plugin@latest;
npm install babel-preset-minify --save-dev;

npm i @babel/polyfill@latest;
npm i @babel/runtime@latest;
npm i @babel/runtime-corejs2@latest;
npm i @hot-loader/react-dom@latest;
npm i axios@latest;
npm i classnames@latest;
npm i es6-promise@latest;
npm i lodash@latest;
npm i moment@latest;
npm i normalize.css@latest;
npm i prop-types@latest;
npm i qs@latest;
npm i react@latest;
npm i react-dom@latest;
npm i react-loadable@latest;
npm i react-redux@latest;
npm i react-router-dom@latest;
npm i react-sizeme@latest;
npm i redux@latest;
npm i redux-actions@latest;
npm i redux-saga@latest;
npm i reselect@latest;
npm i uuid@latest;
npm i validator@latest;
