npm i -D @babel/cli@latest;
npm i -D @babel/core@latest;
npm i -D @babel/plugin-external-helpers@latest;
npm i -D @babel/plugin-proposal-class-properties@latest;
npm i -D @babel/plugin-proposal-export-default-from@latest;
npm i -D @babel/plugin-syntax-dynamic-import@latest;
npm i -D @babel/plugin-transform-arrow-functions@latest;
npm i -D @babel/plugin-transform-object-super@latest;
npm i -D @babel/plugin-transform-runtime@latest;
npm i -D @babel/preset-env@latest;
npm i -D @svgr/webpack@latest;
npm i -D babel-eslint@latest;
npm i -D babel-loader@latest;
npm i -D babel-plugin-async-to-promises@latest;
npm i -D babel-plugin-minify-builtins@latest;
npm i -D babel-plugin-named-asset-import@latest;
npm i -D babel-plugin-syntax-async-functions@latest;
npm i -D babel-plugin-transform-async-to-bluebird@latest;
npm i -D babel-plugin-transform-inline-environment-variables@latest;
npm i -D babel-plugin-transform-promise-to-bluebird@latest;
npm i -D brotli-webpack-plugin@latest;
npm i -D case-sensitive-paths-webpack-plugin@latest;
npm i -D compression-webpack-plugin@latest;
npm i -D eslint@latest;
npm i -D eslint-plugin-babel@latest;
npm i -D eslint-plugin-import@latest;
npm i -D html-webpack-plugin@latest;
npm i -D nodemon@latest;
npm i -D optimize-css-assets-webpack-plugin@latest;
npm i -D pnp-webpack-plugin@latest;
npm i -D terser-webpack-plugin@latest;
npm i -D webpack@latest;
npm i -D webpack-cli@latest;
npm i -D webpack-dashboard@latest;
npm i -D webpack-dev-middleware@latest;
npm i -D webpack-dev-server@latest;
npm i -D webpack-hot-middleware@latest;
npm i -D webpack-manifest-plugin@latest;
npm i -D webpack-node-externals@latest;
npm i -D workbox-webpack-plugin@latest;
npm i @babel/plugin-proposal-async-generator-functions@latest;
npm i @babel/polyfill@latest;
npm i @babel/register@latest;
npm i @babel/runtime@latest;
npm i body-parser@latest;
npm i compression@latest;
npm i cookie-parse@latest;
npm i cookie-parser@latest;
npm i cors@latest;
npm i express@latest;
npm i express-jwt@latest;
npm i helmet@latest;
npm i jsonwebtoken@latest;
npm i mongoose@latest;
npm i validator@latest;
